version: '2.1'

volumes:
  unms_data:
  unifi_config:
  unifi_log:
  unifi_log2:
  unifi_run:
  unifi_run2:
  unifi_work:
  
  
services:
  unifi:
    image: ryansch/unifi-rpi:latest
    container_name: unifi
    network_mode: host
    restart: always
    environment:
      JAVA_OPTS: -Xmx512M
    ports:
      # See https://help.ubnt.com/hc/en-us/articles/218506997-UniFi-Ports-Used
      - "3478:3478/udp"
      - "5514:5514"
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "6789:6789"
      - "27117:27117"
      - "1900:1900/udp"
      - "10001:10001/udp"
    volumes:
      # Unifi v5.0.7 creates all of these directories (some remain empty)
      - unms_config:/var/lib/unifi
      - unms_log:/usr/lib/unifi/logs
      - unms_log2:/var/log/unifi
      - unms_run:/usr/lib/unifi/run
      - unms_run2:/run/unifi
      - unms_work:/usr/lib/unifi/work

  unms:
    build: ./unms
    ports:
      - "4443:443"
      - "4080:80"
      - "2025:2025/udp"
    environment:
      - TZ=${TIME_ZONE:-America/New_York}
      - SECURE_LINK_SECRET=${SEC_LINK_SECRET}
      - PUBLIC_HTTPS_PORT=4443
      - PUBLIC_WS_PORT=4443
    volumes:
      - unms_data:/config
